<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
[
	{
		"prod_no":"C0001",
		"prod_name":"아메리카노",
		"prod_price":1000
	},
	{
		"prod_no":"C0002",
		"prod_name":"아이스아메리카노",
		"prod_price":1000
	},
	{
		"prod_no":"S0001",
		"prod_name":"수박주스",
		"prod_price":4000
	},
	{
		"prod_no":"S0002",
		"prod_name":"팥빙수",
		"prod_price":8000
	}
]